In [124]:
import torch
import numpy as np

In [125]:
#load the mnist data     x denotes the samples while y denotes the labels
(x_train, y_train, x_test, y_test)=torch.load('mnist.pt')

In [126]:
# convert the image(28*28 dimensions) to 1*784 dimension vector
x_train1 = []
for data_point in x_train:
    x_train1.append(data_point.view(1,-1)[0])
    
x_test1 = []

for data_point in x_test:
    x_test1.append(data_point.view(1,-1)[0])

In [172]:
print((x_train).shape)
print((x_test).shape)
print(len(x_train1))
print(len(x_test))

torch.Size([1000, 28, 28])
torch.Size([100, 28, 28])
1000
100


In [173]:
print(len(x_train1[0]))

784


In [174]:
x_train.shape

torch.Size([1000, 28, 28])

In [130]:
# x_train1 consists of 1000 vectors with dimensions 1*784 
# x_test1 consists of 100 vectors with dimensions 1*784 
x_train1[0] 

tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
         18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 1

In [131]:
# now we find the distance between 2 temsors
def euclideanDistance(sample1,sample2):
    return distance.euclidean(sample1.numpy(),sample2.numpy())

In [132]:
import matplotlib.pyplot as plt
from scipy.spatial import distance
import functools
import operator

In [133]:
# comparator which will be  useful for sorting neighbors 
def mycmp(i1,i2):
    if i1[1]<i2[1]:
        return -1
    elif i1[1]>i2[1]: 
        return 1
    else:
        if i1[3]<i2[3]:  # if both values are equal it sorts with respect to index
            return -1
        else:
            return 1
        

In [134]:
# find the k nearest neighbors in the form of tuples where each tuple is of the form (data point, distance,label,index)

def neighbors(training_set,test_sample,k,training_labels):
    distances = []
    
    for i in range(len(training_set)):
        dist = euclideanDistance(training_set[i],test_sample)
        distances.append((training_set[i],dist,training_labels[i],i))

    distances = sorted(distances,key=functools.cmp_to_key(mycmp))
    neighbors_list = []
    for i in range(k):
        neighbors_list.append(distances[i])
        
    return neighbors_list
    

In [176]:
k = input("Enter the Value of K:")

Enter the Value of K:1


In [177]:

#predicting labels for each test instance
predictions = []
for i in range(len(x_test1)):
    neighbors_list = neighbors(x_train1,x_test1[i],int(k),y_train) #returns neighbour list for a particular test sample
    labels=np.zeros(10) #list of 10 zeros indicating votes
    for i in range(int(k)):
        resp = neighbors_list[i][2] #label of each element in neighbours list
        labels[resp]+=1
    labels_sorted=sorted(labels,reverse=True) #sorts labels in descending order
    for i in range(len(labels)):
        if(labels[i]==labels_sorted[0]): #finds class having maximum votes
            predictions.append(i)
            break

In [178]:
#list of predictions
print(predictions)

[7, 1, 1, 1, 4, 1, 1, 1, 1, 7, 1, 8, 4, 1, 1, 1, 4, 7, 1, 4, 1, 6, 1, 6, 4, 1, 7, 4, 0, 1, 1, 1, 1, 4, 7, 7, 7, 1, 1, 1, 1, 7, 1, 1, 1, 1, 1, 2, 1, 4, 6, 1, 4, 5, 8, 0, 5, 1, 7, 1, 1, 1, 9, 1, 7, 4, 1, 4, 1, 1, 7, 1, 8, 1, 1, 1, 1, 7, 1, 7, 9, 1, 2, 7, 1, 1, 7, 1, 1, 1, 1, 4, 9, 1, 1, 1, 1, 1, 6, 1]


In [179]:
#list of original labels
print(list(y_test.numpy()))

[7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6, 5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6, 9, 3, 1, 4, 1, 7, 6, 9]


In [180]:
#finding accuracy of predictions based on original labels
from sklearn.metrics import accuracy_score
print(accuracy_score(list(y_test.numpy()),predictions)*100)

43.0


In [171]:

y_true=list(y_test.numpy())
y_pred=predictions
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true, y_pred)
print(cm)

[[ 2  6  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0]
 [ 0  3  2  0  0  0  0  2  1  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  8  1  0  0  0  0]
 [ 0  4  0  0  1  1  1  0  0  0]
 [ 0  4  0  0  1  0  3  0  2  0]
 [ 0  3  0  0  0  0  0 11  0  1]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  2  0  0  2  0  2]]
