In [1]:
import torch
import numpy as np

In [2]:
#loading cifar 10 dataset
(x_train, y_train, x_test, y_test)=torch.load('cifar10.pt')

In [3]:
x_train[0].size()

torch.Size([32, 32, 3])

In [19]:
#making 32*32*3 image to 1*3072 dimension feature vector
x_train1 = []
for i in x_train:
    x_train1.append(i.view(1,-1)[0])
x_test1 = []

for i in x_test:
    x_test1.append(i.view(1,-1)[0])

In [20]:
#converting 3072 dimension vector to 765 dimension tensor by frequencies of hisograms of R,G,B planes
train_data = []
for i in X_train:
    lis = []
    lis = lis +  list(np.histogram(i[0:1024],[j for j in range(256)])[0])
    lis = lis + list(np.histogram(i[1024:2048],[j for j in range(256)])[0])
    lis = lis + list(np.histogram(i[2048:3072],[j for j in range(256)])[0])
    train_data.append(torch.tensor(lis))
    
test_data = []

for i in X_test:
    lis = []
    lis = lis +  list(np.histogram(i[0:1024],[j for j in range(256)])[0])
    lis = lis + list(np.histogram(i[1024:2048],[j for j in range(256)])[0])
    lis = lis + list(np.histogram(i[2048:3072],[j for j in range(256)])[0])
    test_data.append(torch.tensor(lis))

In [31]:
print(len(train_data[0]))

765


In [21]:
train_labels = list(y_train.numpy().flatten())
test_labels = list(y_test.numpy().flatten())

In [55]:
# taking value of k from user
k = input("enter the value of k")

enter the value of k5


In [56]:
# now we find the distance between 2 tensors
def euclideanDistance(sample1,sample2):
    return distance.euclidean(sample1.numpy(),sample2.numpy())

In [57]:
import matplotlib.pyplot as plt
from scipy.spatial import distance
import functools
import operator

In [58]:
# comparator which will be  useful for sorting neighbors 
def mycmp(i1,i2):
    if i1[1]<i2[1]:
        return -1
    elif i1[1]>i2[1]:
        return 1
    else:
        if i1[3]<i2[3]: # equal values are sorted based on the value of index
            return -1
        else:
            return 1
        

In [59]:
# find the k nearest neighbors in the form of tuples where each tuple is of the form (data point, distance,label,index)

def neighbors(training_set,test_sample,k,training_labels):
    distances = []
    
    for i in range(len(training_set)):
        dist = euclideanDistance(training_set[i],test_sample)
        distances.append((training_set[i],dist,training_labels[i],i))

    distances = sorted(distances,key=functools.cmp_to_key(mycmp))
    neighbors_list = []
    for i in range(k):
        neighbors_list.append(distances[i])
        
    return neighbors_list
    

In [60]:

#predicting labels for each test instance
predictions = []
for i in range(len(x_test)):
    neighbors_list = neighbors(x_train1,x_test1[i],int(k),y_train) #returns neighbour list for a particular test sample
    labels=np.zeros(10) #list of 10 zeros indicating votes
    for i in range(int(k)):
        resp = neighbors_list[i][2] #label of each element in neighbours list
        labels[resp]+=1
    labels_sorted=sorted(labels,reverse=True) #sorts labels in descending order
    for i in range(len(labels)):
        if(labels[i]==labels_sorted[0]): #finds class having maximum votes
            predictions.append(i)
            break

In [61]:
print(predictions)

[0, 0, 8, 0, 2, 2, 2, 4, 0, 1, 0, 8, 0, 4, 0, 0, 2, 8, 4, 0, 0, 1, 0, 2, 2, 8, 2, 4, 0, 2, 2, 0, 0, 2, 8, 0, 0, 4, 0, 2, 0, 4, 0, 4, 2, 0, 0, 0, 6, 2, 0, 8, 3, 3, 8, 8, 7, 0, 0, 2, 0, 2, 4, 4, 0, 5, 0, 2, 8, 5, 0, 5, 0, 8, 4, 2, 0, 9, 2, 6, 1, 0, 2, 2, 0, 0, 0, 4, 4, 0, 0, 2, 4, 8, 0, 0, 0, 0, 6, 5]


In [62]:
#finding accuracy of predictions based on original labels
from sklearn.metrics import accuracy_score
print(accuracy_score(list(y_test.numpy()),predictions)*100)

14.000000000000002


In [63]:

y_true=list(y_test.numpy())
y_pred=predictions
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true, y_pred)
print(cm)

[[4 1 1 1 2 0 1 0 0 0]
 [2 1 2 0 1 0 0 0 0 0]
 [4 0 2 0 0 1 0 0 1 0]
 [3 0 3 1 1 0 0 0 1 1]
 [6 0 1 0 0 0 0 0 0 0]
 [4 0 4 0 0 0 0 0 0 0]
 [4 0 6 0 4 1 0 0 1 0]
 [3 0 1 0 2 2 1 1 1 0]
 [3 1 0 0 3 0 1 0 5 0]
 [8 0 1 0 0 0 0 0 2 0]]
